# Generated by Django 5.2 on 2025-04-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_almacen_categorias_descuento_tipodepago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idCategorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('idAlmacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.almacen')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.producto')),
            ],
        ),
    ]
